# Custom Language File for Launcher Customizer

[ejs.app]
title = "아생서버 런처"

[ejs.landing]
mediaGitHubURL = "https://chzzk.naver.com/live/cb426cc33cebf9231d515df1e2ef482b"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "https://www.youtube.com/@iceearth"
mediaDiscordURL = "https://discord.gg/g4MyZyJ"

[ejs.settings]
sourceGithubLink = "https://github.com/IceEarth-Offical/IceearthLauncher"
supportLink = "https://github.com/IceEarth-Offical/IceearthLauncher/issues"

[ejs.welcome]
welcomeHeader = "아생서버에 오신것을 환영합니다"
welcomeDescription = "재밌는 아생서버를 즐겨보세요"
welcomeDescCTA = "어떻게 할지 모른다고요? 클릭만 하세요."
